name: Lint with pylint

on:
  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint jupyter nbconvert autopep8

      - name: Convert notebooks to Python scripts
        run: |
          jupyter nbconvert --to script *.ipynb

      - name: Auto-format with autopep8
        run: |
          autopep8 --in-place --aggressive --aggressive *.py

      - name: Run pylint on converted notebooks
        run: |
          pylint *.py
